CREATE DATABASE TASKMANAGERKIDS;

USE TASKMANAGERKIDS;

CREATE TABLE KID(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(70) NOT NULL,
	USER VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	SCORE INT NOT NULL,
	PROFILE BLOB
);

INSERT INTO KID(NAME, USER, PASSWORD, SCORE)
VALUES ("Gustavo Eduardo", "gustavo123", "Gust4v0$", 0);

CREATE TABLE PARENT(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(70) NOT NULL,
	USER VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	PROFILE BLOB
);

INSERT INTO PARENT(NAME, USER, PASSWORD)
VALUES ("José Eduardo", "jose123", "J0s3$");

CREATE TABLE PARENT_KID(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDKID INT NOT NULL,
	IDPARENT INT NOT NULL,
	FOREIGN KEY (IDKID) REFERENCES KID(ID),
	FOREIGN KEY (IDPARENT) REFERENCES PARENT(ID)
);

INSERT INTO PARENT_KID(IDKID, IDPARENT)
VALUES (1, 1);

CREATE TABLE TODO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY VARCHAR(50) NOT NULL,
  TOPIC VARCHAR(30) NOT NULL,
  TITLE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  STATUS VARCHAR(30) NOT NULL,
  IMPORTANCE VARCHAR(10) NOT NULL,
  RESPONSIBLEID INT NOT NULL,
  GAINSCORE INT NOT NULL,
  FOREIGN KEY (RESPONSIBLEID) REFERENCES KID(ID)
);
INSERT INTO TODO(CATEGORY, TOPIC, TITLE, DESCRIPTION, STATUS, IMPORTANCE, RESPONSIBLEID, GAINSCORE)
VALUES ("Tarefa Doméstica", "Limpeza", "Retirar o lixo", "Favor recolher o lixo antes das 10 horas", "Aguardando", "Alta", 1, 20);
